/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    User: {
      uid: string
      email: string
      fullName: string
      status: string
      deletedAt?: string
    }
    UserCreate: components['schemas']['User'] & { password: string }
    UserUpdate: { fullName: string; status: string; password: string }
    LoginRequest: { email: string; password: string }
    Question: {
      uid?: string
      question: string
      answers: { [key: string]: string }
      isMultiple?: boolean
    }
    QuestionRequest: {
      question: string
      answers: { [key: string]: string }
      rightAnswers: number[]
    }
    Quiz: {
      uid: string
      title: string
      createdById?: string
      createdBy: components['schemas']['User']
      questionsCount?: number
      time?: string
      questions: components['schemas']['Question'][]
      rightAnswers?: number[]
      deletedAt?: string
    }
    CreateQuiz: {
      title: string
      time?: string
      questions: components['schemas']['QuestionRequest'][]
    }
    ResultRequest: { userUid?: string; quizUid?: string }
    QuizQuestionAnswer: { questionId?: string; userAnswers: number[] }
    QuizResult: {
      quizId?: string
      questions: components['schemas']['QuizQuestionAnswer'][]
    }
    Result: {
      uid?: string
      score?: string
      finishedAt?: string
      user?: { uid?: string; email?: string; fullName?: string }
      quiz?: { uid?: string; title?: string; createdBy?: string }
    }
  }
}
