/**
 * This file was auto-generated by swagger-to-ts.
 * Do not make direct changes to the file.
 */

export interface components {
  schemas: {
    User: { uid: string; email: string; fullName: string; status: string }
    UserCreate: components['schemas']['User'] & { password: string }
    LoginRequest: { email: string; password: string }
    Question: {
      uid?: string
      question: string
      answers: { [key: string]: string }
      rightAnswers: number[]
    }
    Quiz: {
      uid: string
      title: string
      createdById?: string
      createdBy: components['schemas']['User']
      questionsCount?: number
      time?: string
    }
    CreateQuiz: {
      title: string
      time?: string
      questions: components['schemas']['Question'][]
    }
    QuizDetails: components['schemas']['Quiz'] & components['schemas']['CreateQuiz']
    ResultRequest: { userUid?: string; quizUid?: string }
    Result: {
      uid?: string
      score?: string
      finishedAt?: string
      user?: { uid?: string; email?: string; fullName?: string }
      quiz?: { uid?: string; title?: string; createdBy?: string }
    }
  }
}
